/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperos.cloudshellconfig.utils.cloudtty;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * VirtualServiceConfig specifies some of the parameters necessary to create the virtaulService.
 */
@ApiModel(description = "VirtualServiceConfig specifies some of the parameters necessary to create the virtaulService.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-23T07:59:07.811Z[Etc/UTC]")
public class V1alpha1CloudShellSpecVirtualServiceConfig {
  public static final String SERIALIZED_NAME_EXPORT_TO = "export_to";
  @SerializedName(SERIALIZED_NAME_EXPORT_TO)
  private String exportTo;

  public static final String SERIALIZED_NAME_GATEWAY = "gateway";
  @SerializedName(SERIALIZED_NAME_GATEWAY)
  private String gateway;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_VIRTUAL_SERVICE_NAME = "virtualServiceName";
  @SerializedName(SERIALIZED_NAME_VIRTUAL_SERVICE_NAME)
  private String virtualServiceName;


  public V1alpha1CloudShellSpecVirtualServiceConfig exportTo(String exportTo) {
    
    this.exportTo = exportTo;
    return this;
  }

   /**
   * The value \&quot;.\&quot; is reserved and defines an export to the same namespace that the virtual service is declared in. Similarly the value \&quot;*\&quot; is reserved and defines an export to all namespaces.
   * @return exportTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The value \".\" is reserved and defines an export to the same namespace that the virtual service is declared in. Similarly the value \"*\" is reserved and defines an export to all namespaces.")

  public String getExportTo() {
    return exportTo;
  }


  public void setExportTo(String exportTo) {
    this.exportTo = exportTo;
  }


  public V1alpha1CloudShellSpecVirtualServiceConfig gateway(String gateway) {
    
    this.gateway = gateway;
    return this;
  }

   /**
   * Gateway must be specified and the gateway already exists in the cluster.
   * @return gateway
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Gateway must be specified and the gateway already exists in the cluster.")

  public String getGateway() {
    return gateway;
  }


  public void setGateway(String gateway) {
    this.gateway = gateway;
  }


  public V1alpha1CloudShellSpecVirtualServiceConfig namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Namespace specifies a namespace that the virtualService will be created in it. if it&#39;s empty, default the cloudshell namespace.
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Namespace specifies a namespace that the virtualService will be created in it. if it's empty, default the cloudshell namespace.")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  public V1alpha1CloudShellSpecVirtualServiceConfig virtualServiceName(String virtualServiceName) {
    
    this.virtualServiceName = virtualServiceName;
    return this;
  }

   /**
   * VirtualServiceName specifies a name to virtualService, if it&#39;s empty, default \&quot;cloudshell-VirtualService\&quot;
   * @return virtualServiceName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "VirtualServiceName specifies a name to virtualService, if it's empty, default \"cloudshell-VirtualService\"")

  public String getVirtualServiceName() {
    return virtualServiceName;
  }


  public void setVirtualServiceName(String virtualServiceName) {
    this.virtualServiceName = virtualServiceName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CloudShellSpecVirtualServiceConfig v1alpha1CloudShellSpecVirtualServiceConfig = (V1alpha1CloudShellSpecVirtualServiceConfig) o;
    return Objects.equals(this.exportTo, v1alpha1CloudShellSpecVirtualServiceConfig.exportTo) &&
        Objects.equals(this.gateway, v1alpha1CloudShellSpecVirtualServiceConfig.gateway) &&
        Objects.equals(this.namespace, v1alpha1CloudShellSpecVirtualServiceConfig.namespace) &&
        Objects.equals(this.virtualServiceName, v1alpha1CloudShellSpecVirtualServiceConfig.virtualServiceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exportTo, gateway, namespace, virtualServiceName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CloudShellSpecVirtualServiceConfig {\n");
    sb.append("    exportTo: ").append(toIndentedString(exportTo)).append("\n");
    sb.append("    gateway: ").append(toIndentedString(gateway)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    virtualServiceName: ").append(toIndentedString(virtualServiceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

