/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperos.cloudshellconfig.utils.cloudtty;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SecretRef represents the secret contains mandatory credentials to access the target cluster. The secret should hold credentials as follows: - secret.data.token - secret.data.caBundle The field is alpha phase, paleas open the featuregate AllowSecretStoreKubeconfig to use it.
 */
@ApiModel(description = "SecretRef represents the secret contains mandatory credentials to access the target cluster. The secret should hold credentials as follows: - secret.data.token - secret.data.caBundle The field is alpha phase, paleas open the featuregate AllowSecretStoreKubeconfig to use it.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-23T07:59:07.811Z[Etc/UTC]")
public class V1alpha1CloudShellSpecSecretRef {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public V1alpha1CloudShellSpecSecretRef name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name is the name of resource being referenced.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name is the name of resource being referenced.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CloudShellSpecSecretRef v1alpha1CloudShellSpecSecretRef = (V1alpha1CloudShellSpecSecretRef) o;
    return Objects.equals(this.name, v1alpha1CloudShellSpecSecretRef.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CloudShellSpecSecretRef {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

