/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hyperos.cloudshellconfig.utils.cloudtty;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Most recently observed status of the cloudshell.
 */
@ApiModel(description = "Most recently observed status of the cloudshell.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-09-23T07:59:07.811Z[Etc/UTC]")
public class V1alpha1CloudShellStatus {
  public static final String SERIALIZED_NAME_ACCESS_URL = "accessUrl";
  @SerializedName(SERIALIZED_NAME_ACCESS_URL)
  private String accessUrl;

  public static final String SERIALIZED_NAME_LAST_SCHEDULE_TIME = "lastScheduleTime";
  @SerializedName(SERIALIZED_NAME_LAST_SCHEDULE_TIME)
  private OffsetDateTime lastScheduleTime;

  public static final String SERIALIZED_NAME_PHASE = "phase";
  @SerializedName(SERIALIZED_NAME_PHASE)
  private String phase;


  public V1alpha1CloudShellStatus accessUrl(String accessUrl) {
    
    this.accessUrl = accessUrl;
    return this;
  }

   /**
   * Get accessUrl
   * @return accessUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAccessUrl() {
    return accessUrl;
  }


  public void setAccessUrl(String accessUrl) {
    this.accessUrl = accessUrl;
  }


  public V1alpha1CloudShellStatus lastScheduleTime(OffsetDateTime lastScheduleTime) {
    
    this.lastScheduleTime = lastScheduleTime;
    return this;
  }

   /**
   * Information when was the last time the pod was successfully scheduled.
   * @return lastScheduleTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Information when was the last time the pod was successfully scheduled.")

  public OffsetDateTime getLastScheduleTime() {
    return lastScheduleTime;
  }


  public void setLastScheduleTime(OffsetDateTime lastScheduleTime) {
    this.lastScheduleTime = lastScheduleTime;
  }


  public V1alpha1CloudShellStatus phase(String phase) {
    
    this.phase = phase;
    return this;
  }

   /**
   * INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \&quot;make\&quot; to regenerate code after modifying this file
   * @return phase
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"make\" to regenerate code after modifying this file")

  public String getPhase() {
    return phase;
  }


  public void setPhase(String phase) {
    this.phase = phase;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1CloudShellStatus v1alpha1CloudShellStatus = (V1alpha1CloudShellStatus) o;
    return Objects.equals(this.accessUrl, v1alpha1CloudShellStatus.accessUrl) &&
        Objects.equals(this.lastScheduleTime, v1alpha1CloudShellStatus.lastScheduleTime) &&
        Objects.equals(this.phase, v1alpha1CloudShellStatus.phase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessUrl, lastScheduleTime, phase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1CloudShellStatus {\n");
    sb.append("    accessUrl: ").append(toIndentedString(accessUrl)).append("\n");
    sb.append("    lastScheduleTime: ").append(toIndentedString(lastScheduleTime)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

